export interface TranscriptSegment {
  start: number;
  end: number;
  text: string;
}

export interface Transcript {
  language: string;
  isAutoGenerated?: boolean;
  segments: TranscriptSegment[];
}

export interface Video {
  id: string;
  title: string;
  channelTitle: string;
  duration: number;
  thumbnailUrl?: string;
  localPath?: string;
  transcriptPath?: string;
  transcript?: Transcript;
  // Multiple transcripts for different languages
  transcripts?: Transcript[];
}

export interface RemoteVideo {
  id: string;
  title: string;
  channelTitle: string;
  duration: number;
  fileSize: number;
  hasTranscript: boolean;
  thumbnailUrl?: string;
  // Available transcript languages
  availableLanguages?: string[];
}

export interface ServerInfo {
  name: string;
  version: string;
  videoCount: number;
}

export interface VideoMeta {
  id: string;
  title: string;
  channelTitle: string;
  duration: number;
  transcript?: Transcript;
  // Multiple transcripts from server
  transcripts?: Transcript[];
}

// Translation types for vocabulary learning
export interface Translation {
  id: string;
  sourceText: string;
  sourceLang: string;
  targetLang: string;
  translatedText: string;
  detectedLang?: string;
  queryCount: number;
  contexts?: TranslationContext[];
}

export interface TranslationContext {
  videoId: string;
  timestampSeconds: number;
  contextText?: string;
}

export interface SavedWord {
  id: string;
  translation: Translation;
  notes?: string;
  reviewCount: number;
  lastReviewedAt?: number;
}

// P2P Sharing Types
export interface DiscoveredPeer {
  name: string;
  host: string;
  port: number;
  videoCount: number;
}

export interface PeerVideo {
  id: string;
  title: string;
  channelTitle: string;
  duration: number;
  hasTranscript: boolean;
}

export interface TransferProgress {
  videoId: string;
  title: string;
  progress: number;
  status: "pending" | "downloading" | "completed" | "failed";
}
