import type { ServerInfo, RemoteVideo, VideoMeta, Transcript } from "../types";

const TIMEOUT = 10000;

// Response type for transcripts endpoint
interface TranscriptsResponse {
  transcripts: Array<{
    language: string;
    isAutoGenerated: boolean;
    segments: Array<{ start: number; end: number; text: string }>;
  }>;
}

async function fetchWithTimeout(
  url: string,
  options: RequestInit = {},
  timeout = TIMEOUT
): Promise<Response> {
  const controller = new AbortController();
  const id = setTimeout(() => controller.abort(), timeout);

  try {
    const response = await fetch(url, {
      ...options,
      signal: controller.signal,
    });
    return response;
  } finally {
    clearTimeout(id);
  }
}

export const api = {
  async getInfo(serverUrl: string): Promise<ServerInfo> {
    const response = await fetchWithTimeout(`${serverUrl}/api/info`);
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }
    return response.json();
  },

  async getVideos(serverUrl: string): Promise<{ videos: RemoteVideo[] }> {
    const response = await fetchWithTimeout(`${serverUrl}/api/videos`);
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }
    return response.json();
  },

  async getVideoMeta(serverUrl: string, videoId: string): Promise<VideoMeta> {
    const response = await fetchWithTimeout(
      `${serverUrl}/api/video/${videoId}/meta`
    );
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }
    return response.json();
  },

  getVideoFileUrl(serverUrl: string, videoId: string): string {
    return `${serverUrl}/api/video/${videoId}/file`;
  },

  getTranscriptUrl(serverUrl: string, videoId: string): string {
    return `${serverUrl}/api/video/${videoId}/transcript`;
  },

  getThumbnailUrl(serverUrl: string, videoId: string): string {
    return `${serverUrl}/api/video/${videoId}/thumbnail`;
  },

  // Fetch all transcripts for a video (multiple languages)
  async getVideoTranscripts(
    serverUrl: string,
    videoId: string
  ): Promise<Transcript[]> {
    try {
      const response = await fetchWithTimeout(
        `${serverUrl}/api/video/${videoId}/transcripts`
      );
      if (!response.ok) {
        // Fall back to single transcript if multi-transcript endpoint doesn't exist
        if (response.status === 404) {
          const meta = await this.getVideoMeta(serverUrl, videoId);
          return meta.transcript ? [meta.transcript] : [];
        }
        throw new Error(`HTTP ${response.status}`);
      }
      const data: TranscriptsResponse = await response.json();
      return data.transcripts;
    } catch (error) {
      // Fall back to single transcript from meta
      console.log(
        "[API] Multi-transcript endpoint failed, falling back to meta"
      );
      const meta = await this.getVideoMeta(serverUrl, videoId);
      return meta.transcripts ?? (meta.transcript ? [meta.transcript] : []);
    }
  },
};
